### ISSUE TITLE
Information of computing power consumption

### ISSUE THREAD

**Issue by surefyyq** [thu-ml/unidiffuser#1]
Would you please release some datasheet about the required RAM occupation using different graphics card when generating images, as well as the time taken to output images of different resolutions?

**Comment by baofff** [comment]
Thanks for the advice. UniDiffuser can run on a GPU with at least 10 GB memory. We update this information.
As for the time, it depends on the specific device. We have tested it on A100, sampling an image (512x512 resolution) with 50 DPM-Solver steps takes around 3.2s.

**Comment by surefyyq** [comment]
Thanks for your **_OPEN_** work!
