### ISSUE TITLE
About training cost and model size

### ISSUE THREAD

**Issue by sunyoe** [thu-ml/unidiffuser#10]
Thanks for your sharing about unidiffuser.
But I want to know how large the model trained in your experiments, i didn't find details about parameters or flops.
I'm looking forward to your answers, thank you~

**Comment by NieShenRuc** [comment]
The model size of UniDiffuser is 952 M, and the FLOPs is about 1163G.

**Comment by cf2333** [comment]
> 

Hello, Why is this size inconsistent with the size of pre-trained model？

**Comment by cf2333** [comment]
> The model size of UniDiffuser is 952 M, and the FLOPs is about 1163G.

Hello, Why is this size inconsistent with the size of pre-trained model？

**Comment by NieShenRuc** [comment]
> > The model size of UniDiffuser is 952 M, and the FLOPs is about 1163G.
> 
> Hello, Why is this size inconsistent with the size of pre-trained model？

More precisely, the parameter of the UViT part in unidiffuser is 952M, and UViT requires 3.81G of disk space to store.

**Comment by sunyoe** [comment]
Thanks for your answer!
