### ISSUE TITLE
Some questions about unidiffuser paper

### ISSUE THREAD

**Issue by orchidmalevolence** [thu-ml/unidiffuser#14]
Thanks for sharing your work! Good multi-modal for now! Some questions I'd like to ask after reading your paper.
* 1. About training algorithm1, is it really necessary to sample $t^x$, $t^y$ from the whole T $\times$ T joint distribution? Since during inference, we only sample [ $t^x$ from T to 1 with $t^y=0$ ] or  [ $t^y$ from T to 1 with $t^x=0$ ] or [ $t^x$, $t^y$ both from T to 1 with $t^x=t^y$ ].
In other words, see the figure below, what if we only sample $t^x$ , $t^y$ from '-' '|' '/' points during training instead of every points in the square? Will the training still converge and generate well?

                T
                ------------------
                |               /|
                |            /   |
            ty  |         /      |
                |      /         |
                |   /            |
                |/               |
                ------------------
                0      tx        T

* 2. About downsteam tasks, can we do super-resolution on unidiffuser directly without finetuning or additional modules? After using unidiffuser and reading your previous work U-ViT, I tried do super-resolution by treating LR as condtion tokens together with prompt tokens following t2i mode, but got bad output. Is there a easy and no-finetuning way performing super-resolution with a nice-pretrained unified generation model?
If addtional modules are inevitable, is ControlNet a good way?

* 3. About img and txt encoders, why do we need an additional CLIP img encoder? And why CLIP instead of a pure txt tokenizer like BPE? From my view, it's a little tricky to use such an already cross-modality encoder to train a multi-modal generation model.

Much appreciate if you can take a look sometime. :)

**Comment by baofff** [comment]
1. Yes.
2. Super-resolution has strong spatial correspondance. Treating LR as condition tokens might be hard to train. Perhaps you can try concat LR and $x_t$ before feeding them to U-Vit.
3. CLIP captures the semantic information in an image, which eases the image-to-text task.

**Comment by orchidmalevolence** [comment]
Many thx! I will try your advice on SR!

**Comment by shencuifeng** [comment]
> 1. Yes.
> 2. Super-resolution has strong spatial correspondance. Treating LR as condition tokens might be hard to train. Perhaps you can try concat LR and xt before feeding them to U-Vit.
> 3. CLIP captures the semantic information in an image, which eases the image-to-text task.

if I only want joint distribution, can I just sample [$t^x$ $t^y$ both from 1 to T with $t^x$=$t^y$]?

**Comment by baofff** [comment]
Of course
