### ISSUE TITLE
Generated images using diffusers package code in README are completely black

### ISSUE THREAD

**Issue by SKDDJ** [thu-ml/unidiffuser#34]
The images generated using the code related to the diffusers package in the README are all black.

**Comment by mazai-xiangji** [comment]
Hello, I also had the same problem, how did you solve it

**Comment by SKDDJ** [comment]
> Hello, I also had the same problem, how did you solve it

Hello, I discovered this reply just now. I reached out to the pipeline author, who mentioned that it's caused by the torch edition.

To resolve this problem, I recommend using **Torch** 2.X instead of 1.X.
