### ISSUE TITLE
Question on License

### ISSUE THREAD

**Issue by cloneofsimo** [thu-ml/unidiffuser#6]
Thank you for the amazing work! I have a question on the license for this model.
It looks like on Huggingface, license is MIT, but immediately mentions that it is intended for research purpose only.
Is that prohibiting commercial usage? And it would be good to have license file on this repo as well.

**Comment by baofff** [comment]
Thanks for the advice. We encourage open-source usage of UniDiffuser, and we have updated our license (agpl-3.0).
